### ISSUE TITLE
ver 2.0 error

### ISSUE THREAD

**Issue by TheDeibo** [ratchetgame98/ServerLove#1]
15:01:30 [INFO] Usage: /serverlove <args>
15:01:30 [INFO] Available Args: Block, Update, Lawyer, DivConf

I used it as player

14:59:52 [ERROR] null
14:59:52 org.bukkit.command.CommandException: Unhandled exception executing command 'serverlove' in plugin ServerLove v2.0
14:59:52 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit_server.jar:git-Bukkit-18fbb24]
14:59:52 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit_server.jar:git-Bukkit-18fbb24]
14:59:52 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:620) ~[craftbukkit_server.jar:git-Bukkit-18fbb24]
14:59:52 at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1106) [craftbukkit_server.jar:git-Bukkit-18fbb24]
14:59:52 at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:966) [craftbukkit_server.jar:git-Bukkit-18fbb24]
14:59:52 at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37) [craftbukkit_server.jar:git-Bukkit-18fbb24]
14:59:52 at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9) [craftbukkit_server.jar:git-Bukkit-18fbb24]
14:59:52 at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit_server.jar:git-Bukkit-18fbb24]
14:59:53 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_66]
14:59:53 at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
14:59:53 at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit_server.jar:git-Bukkit-18fbb24]
14:59:53 at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:673) [craftbukkit_server.jar:git-Bukkit-18fbb24]
14:59:53 at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit_server.jar:git-Bukkit-18fbb24]
14:59:53 at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [craftbukkit_server.jar:git-Bukkit-18fbb24]
14:59:53 at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [craftbukkit_server.jar:git-Bukkit-18fbb24]
14:59:53 at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
14:59:53 Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
14:59:53 at me.ratchetgame98.love.ServerLove.onCommand(ServerLove.java:306) ~[?:?]
14:59:53 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit_server.jar:git-Bukkit-18fbb24]
14:59:53 ... 15

**Comment by ratchetgame98** [comment]
Sorry I'm late addressing this issue. The problem that you have is that the plugin looks for Blocked data in the config, and if nothing in the config is present, will result in an error. I have tried numerous ways of trying to fix this bug but am never getting closer to a fix with the editing of the code. For now, to fix the bug, all the player needs to do is block the person they want to marry/date then unblock them again and it should work fine. I will try to fix this bug whenever possible but for now you'll just have to live with it until a fix is found. Sorry for any inconvenience, I am trying my best to fix this
